### PR TITLE
initialize DateRangePicker with end date

### PR DESCRIPTION
**Pull request by paralen**

### CODE REVIEW

**Comment by Debjyotinath** [comment]
Hi borax12,
When can we use this feature?

**Comment by heysupratim** [comment]
@Debjyotinath - i will be merging the pending PRs today . So dont worry , its coming asap

**Comment by Debjyotinath** [comment]
Thank you.

**Comment by heysupratim** [comment]
@paralen @Debjyotinath merged :) :+1:

**Comment by csbenz** [comment]
@paralen Could you implement the same for the Time Dialog?

**Pull request merged**
