### PR TITLE
Initialize Time picker with end time

### PR DESCRIPTION
**Pull request by csbenz**

### CODE REVIEW

**Comment by csbenz** [comment]
+1

**Comment by jrejaud** [comment]
Please merge this, this is a very valuable feature :)

**Comment by jrejaud** [comment]
@csbenz Have you considering adding your fork to jitpack? jitpack.io

**Comment by heysupratim** [comment]
@jrejaud - will definitely merge this 👍

**Comment by Kamil-Kaminski** [comment]
@borax12 Hi, how about this feature? When this will be merged?

**Comment by jrejaud** [comment]
@borax12 Bump, I'm waiting on this feature to be merged as well please.

**Pull request merged**
