### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by Kazemir**
So yeah, I did it.

### CODE REVIEW

**Comment by heysupratim** [comment]
@Kazemir my man 👍

**Comment by Kazemir** [comment]
Apparently, it was necessary to use another branch to create another pull-request. I didn't know.

So, I also added a way to create new instanse of dialog with timestamps insteed of using numbers (day/month/year).

**Comment by heysupratim** [comment]
@Kazemir can you try doing that in another PR ?

**Comment by Kazemir** [comment]
Ok, I deleted my last commit

**Pull request merged**
